language: java
install: true

os: linux
dist: trusty
jdk: openjdk11

script:
  - ./gradlew orchidBuild

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build/docs/orchid

notifications:
  email:
    on_success: never
    on_failure: always
