site:
  about:
    siteName: "Rajmahendra's Blog"
    subtitle: 'I have no special telent. I am only passionately curious'
    siteDescription: 'Welcome to my website. You will learn and know more about Java, Kotlin, Community, Fermented food, Sustainable living,Hyderoponic etc.'
    avatar: '/assets/media/logo.jpg'
  theme: 'FutureImperfect'
#  baseUrl: 'netlify'

posts:
  categories:
    - 'personal'
    - 'fermentation'
    - 'sustainable'
    - 'hydroponic'
  permalink: ':category/:year/:monthName/:slug'
  authors:
    - name: 'Author Two'
      avatar: 'assets/images/avatar.jpg'
      email: 'email@domain.tld'
  postPages:
    author: 'Author One'
    layout: single
    components:
      - type: pageContent
      - type: taxonomy
        taxonomyType: tags
      - type: taxonomy
        taxonomyType: categories

theme:
  social:
    facebook: 'facebookUsername'
    twitter: 'twitterHandle'
    instagram: 'instagramHandle'
    github: 'githubUsername'
    other:
      - label: 'linkedin'
        link: 'https://www.example.com'
        icon: 'fa-tag'
  menu:
    - type: 'page'
      title: 'Home'
      url: '/'
    #   - type: "wikiSections"
    - type: 'taxonomy'
      taxonomyType: 'categories'
      includeTerms: true
      termsAtRoot: true
    - type: 'page'
      title: 'About'
      itemId: 'Author One'
    - type: "pages"
      atRoot: true
    - type: groupPages
      collectionType: pages
      collectionId: allPages
  sidebar:
    - type: recentPosts
      limit: 3
      category: gallery
      noWrapper: true
      template:
        - 'includes/postPreview_mini'
    - type: recentPosts
      limit: 5
      category: personal
      noWrapper: true
      template:
        - 'includes/postPreview_list'
  extraCss:
    - 'assets/css/extraCss.scss'
    - 'assets/css/pygments.scss'
  extraJs:
    - 'assets/js/extraJs.js'
  legacySearch: false
  metaComponents:
    - type: orchidSearch

taxonomies:
  collectionArchives:
    - collectionType: 'posts'
  taxonomies:
    - key: tags
      single: false
      orderBy:
        - entryCount
    - key: categories
      single: false
      singleKey: category
      orderBy:
        - year
        - month
        - title
